language: python

git:
  depth: 3

install:
  - pip install -r requirements.txt
  - npm install

script:
  - python example-parser.py example-election-data.xlsx example-election-result.csv 
  - node_modules/csv-test/bin/csv-test tests/csv-test-config.yml example-election-result.csv tests/csv-test-validators.yml
  - cd tests
  - behave -T -q --format pretty
