language: python

git:
  depth: 3

install:
  - pip install -r requirements.txt
  - npm install

script:
  - python parser.py example-election.xlsx results/example-election.csv 
  - node_modules/csv-test/bin/csv-test tests/csv-test-config.yml 'results/*' tests/csv-test-validators.yml
  - cd tests
  - behave -T -q --format pretty
